/**
 * loadtest/spec.js — Production-grade k6 load test for NevUp Track 1
 *
 * Validates:
 *   1. WRITE PATH: POST /trades — sustain ≥200 concurrent req/s, p95 ≤ 150ms
 *   2. READ PATH:  GET /users/:id/metrics — p95 ≤ 200ms
 *
 * Concurrency model:
 *   Each VU iteration includes a 500ms think-time after the HTTP call.
 *   At 200 req/s arrival rate, this forces k6 to maintain ~100 active VUs
 *   concurrently — proving the system handles true parallel load, not just
 *   a single fast-loop VU.
 *
 * Usage:
 *   K6_WEB_DASHBOARD=true k6 run loadtest/spec.js
 */

import http from 'k6/http';
import { check, sleep } from 'k6';
import { Trend, Counter } from 'k6/metrics';
import { SharedArray } from 'k6/data';

// ── Custom Metrics ──────────────────────────────────────────────────────────

const writeLatency = new Trend('write_latency', true);
const readLatency  = new Trend('read_latency', true);
const writeSuccess = new Counter('write_success');
const readSuccess  = new Counter('read_success');
const writeErrors  = new Counter('write_errors');
const readErrors   = new Counter('read_errors');

// Think-time to force concurrent VU overlap.
// At 200 req/s with 500ms think-time: k6 must keep ~100 VUs active simultaneously.
// This proves true concurrent load, not a single-VU fast-loop.
const THINK_TIME_SECONDS = 0.5;

// ── Configuration ───────────────────────────────────────────────────────────

const BASE_URL = __ENV.BASE_URL || 'http://localhost:3000';

// Load user tokens generated by generate_tokens.js
const users = new SharedArray('users', function () {
  return JSON.parse(open('./users.json'));
});

// Enums for randomized payload generation
const ASSET_CLASSES = ['equity', 'crypto', 'forex'];
const DIRECTIONS    = ['long', 'short'];
const STATUSES      = ['open', 'closed'];
const EMOTIONS      = ['calm', 'anxious', 'greedy', 'fearful', 'neutral'];
const GRANULARITIES = ['hourly', 'daily', 'rolling30d'];

const ASSETS = {
  equity: ['AAPL', 'MSFT', 'TSLA', 'GOOG', 'AMZN', 'NVDA', 'META', 'NFLX', 'SPY', 'QQQ'],
  crypto: ['BTC/USDT', 'ETH/USDT', 'SOL/USDT', 'DOGE/USDT', 'ADA/USDT'],
  forex:  ['EUR/USD', 'GBP/USD', 'USD/JPY', 'AUD/USD', 'USD/CAD'],
};

// ── Thresholds ──────────────────────────────────────────────────────────────

export const options = {
  scenarios: {
    // ─── WRITE LOAD: POST /trades ─────────────────────────────────────
    // constant-arrival-rate: guarantees exactly 200 new iterations/sec.
    // With 500ms think-time per iteration, k6 needs ~100 concurrent VUs.
    // preAllocatedVUs=150 ensures no VU starvation; maxVUs=400 for safety.
    trade_write_load: {
      executor: 'constant-arrival-rate',
      exec: 'writeTrade',
      rate: 200,
      timeUnit: '1s',
      duration: '60s',
      preAllocatedVUs: 150,
      maxVUs: 400,
    },

    // ─── READ LOAD: GET /users/:id/metrics ────────────────────────────
    // constant-arrival-rate: guarantees exactly 100 new iterations/sec.
    // With 500ms think-time, k6 needs ~50 concurrent VUs.
    metrics_read_load: {
      executor: 'constant-arrival-rate',
      exec: 'readMetrics',
      rate: 100,
      timeUnit: '1s',
      duration: '60s',
      preAllocatedVUs: 100,
      maxVUs: 300,
    },
  },

  thresholds: {
    // Write path: p95 ≤ 150ms
    'write_latency':  ['p(95)<150'],
    // Read path: p95 ≤ 200ms
    'read_latency':   ['p(95)<200'],
    // Global error rate < 1%
    'http_req_failed': ['rate<0.01'],
    // Dropped iterations must be 0
    'dropped_iterations': ['count==0'],
  },

  // Disable default summary since we use k6 web dashboard
  summaryTrendStats: ['avg', 'min', 'med', 'max', 'p(50)', 'p(90)', 'p(95)', 'p(99)'],
};

// ── Helpers ─────────────────────────────────────────────────────────────────

function randomElement(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function randomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function randomFloat(min, max, decimals = 2) {
  return parseFloat((Math.random() * (max - min) + min).toFixed(decimals));
}

/**
 * Generate a UUID v4 (RFC 4122 compliant)
 * k6 doesn't have crypto.randomUUID, so we implement it manually
 */
function uuidv4() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

/**
 * Generate a random ISO-8601 date within the seed data range
 * Seed data spans roughly 2025-01 to 2025-03
 */
function randomDateInRange() {
  const start = new Date('2025-01-01T00:00:00Z').getTime();
  const end   = new Date('2025-03-31T23:59:59Z').getTime();
  return new Date(start + Math.random() * (end - start)).toISOString();
}

// ── WRITE SCENARIO: POST /trades ────────────────────────────────────────────

export function writeTrade() {
  // Pick a random user (each VU sends trades as different users)
  const user       = randomElement(users);
  const assetClass = randomElement(ASSET_CLASSES);
  const asset      = randomElement(ASSETS[assetClass]);
  const direction  = randomElement(DIRECTIONS);
  const status     = randomElement(STATUSES);
  const entryPrice = randomFloat(10, 5000);
  const quantity   = randomInt(1, 1000);

  const entryAt = randomDateInRange();
  const exitAt  = status === 'closed' ? randomDateInRange() : null;

  const payload = {
    tradeId:        uuidv4(),
    userId:         user.userId,
    sessionId:      user.sessionId,
    asset:          asset,
    assetClass:     assetClass,
    direction:      direction,
    entryPrice:     entryPrice,
    exitPrice:      status === 'closed' ? randomFloat(entryPrice * 0.8, entryPrice * 1.2) : null,
    quantity:       quantity,
    entryAt:        entryAt,
    exitAt:         exitAt,
    status:         status,
    outcome:        status === 'closed' ? randomElement(['win', 'loss', 'breakeven']) : null,
    pnl:            status === 'closed' ? randomFloat(-500, 500) : null,
    planAdherence:  randomInt(1, 5),
    emotionalState: randomElement(EMOTIONS),
    entryRationale: `Load test trade - ${asset} ${direction}`,
    revengeFlag:    Math.random() < 0.1,
  };

  const params = {
    headers: {
      'Content-Type':  'application/json',
      'Authorization': `Bearer ${user.token}`,
    },
    tags: { scenario: 'write' },
  };

  const res = http.post(`${BASE_URL}/trades`, JSON.stringify(payload), params);

  // Record custom metric
  writeLatency.add(res.timings.duration);

  const ok = check(res, {
    'write: status is 200': (r) => r.status === 200,
    'write: has tradeId':   (r) => {
      try {
        const body = r.json();
        return body && (body.tradeId || body.trade_id);
      } catch {
        return false;
      }
    },
  });

  if (ok) {
    writeSuccess.add(1);
  } else {
    writeErrors.add(1);
  }

  // Think-time: keeps this VU "active" for 500ms, forcing k6 to use
  // ~100 parallel VUs to sustain 200 req/s. This proves true concurrency.
  sleep(THINK_TIME_SECONDS);
}

// ── READ SCENARIO: GET /users/:userId/metrics ───────────────────────────────

export function readMetrics() {
  // Pick a random user
  const user        = randomElement(users);
  const granularity = randomElement(GRANULARITIES);

  // Use date range that covers the seed data
  const from = '2025-01-01T00:00:00Z';
  const to   = '2025-03-31T23:59:59Z';

  const url = `${BASE_URL}/users/${user.userId}/metrics?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}&granularity=${granularity}`;

  const params = {
    headers: {
      'Authorization': `Bearer ${user.token}`,
    },
    tags: { scenario: 'read' },
  };

  const res = http.get(url, params);

  // Record custom metric
  readLatency.add(res.timings.duration);

  const ok = check(res, {
    'read: status is 200':    (r) => r.status === 200,
    'read: response is JSON': (r) => {
      try {
        r.json();
        return true;
      } catch {
        return false;
      }
    },
  });

  if (ok) {
    readSuccess.add(1);
  } else {
    readErrors.add(1);
  }

  // Think-time: keeps VU active, forcing ~50 concurrent VUs for reads.
  sleep(THINK_TIME_SECONDS);
}

// ── Summary Handler ─────────────────────────────────────────────────────────

export function handleSummary(data) {
  // Print a clean human-readable summary
  const writeP50 = data.metrics.write_latency ? data.metrics.write_latency.values['p(50)'] : 'N/A';
  const writeP90 = data.metrics.write_latency ? data.metrics.write_latency.values['p(90)'] : 'N/A';
  const writeP95 = data.metrics.write_latency ? data.metrics.write_latency.values['p(95)'] : 'N/A';
  const writeP99 = data.metrics.write_latency ? data.metrics.write_latency.values['p(99)'] : 'N/A';

  const readP50 = data.metrics.read_latency ? data.metrics.read_latency.values['p(50)'] : 'N/A';
  const readP90 = data.metrics.read_latency ? data.metrics.read_latency.values['p(90)'] : 'N/A';
  const readP95 = data.metrics.read_latency ? data.metrics.read_latency.values['p(95)'] : 'N/A';
  const readP99 = data.metrics.read_latency ? data.metrics.read_latency.values['p(99)'] : 'N/A';

  const totalReqs   = data.metrics.http_reqs ? data.metrics.http_reqs.values.count : 0;
  const duration    = data.metrics.http_reqs ? data.metrics.http_reqs.values.rate : 0;
  const failedRate  = data.metrics.http_req_failed ? data.metrics.http_req_failed.values.rate : 0;
  const dropped     = data.metrics.dropped_iterations ? data.metrics.dropped_iterations.values.count : 0;

  const writeCount  = data.metrics.write_success ? data.metrics.write_success.values.count : 0;
  const readCount   = data.metrics.read_success ? data.metrics.read_success.values.count : 0;
  const writeErrCnt = data.metrics.write_errors ? data.metrics.write_errors.values.count : 0;
  const readErrCnt  = data.metrics.read_errors ? data.metrics.read_errors.values.count : 0;

  const summary = `
╔══════════════════════════════════════════════════════════════════╗
║                 NevUp Track 1 — LOAD TEST RESULTS              ║
╠══════════════════════════════════════════════════════════════════╣
║                                                                  ║
║  📊 THROUGHPUT                                                   ║
║  ─────────────────────────────────────────────────────────       ║
║  Total Requests:     ${String(totalReqs).padStart(8)}                               ║
║  Avg Req/s:          ${String(duration.toFixed(1)).padStart(8)}                               ║
║  Write Successes:    ${String(writeCount).padStart(8)}                               ║
║  Read Successes:     ${String(readCount).padStart(8)}                               ║
║  Write Errors:       ${String(writeErrCnt).padStart(8)}                               ║
║  Read Errors:        ${String(readErrCnt).padStart(8)}                               ║
║  Dropped Iterations: ${String(dropped).padStart(8)}                               ║
║  Error Rate:         ${(failedRate * 100).toFixed(3)}%                              ║
║                                                                  ║
║  ✏️  WRITE LATENCY (POST /trades)                                ║
║  ─────────────────────────────────────────────────────────       ║
║  p50:  ${typeof writeP50 === 'number' ? writeP50.toFixed(2) + 'ms' : writeP50}                                                  ║
║  p90:  ${typeof writeP90 === 'number' ? writeP90.toFixed(2) + 'ms' : writeP90}                                                  ║
║  p95:  ${typeof writeP95 === 'number' ? writeP95.toFixed(2) + 'ms' : writeP95}   ${typeof writeP95 === 'number' && writeP95 < 150 ? '✅ PASS' : '❌ FAIL'}                                   ║
║  p99:  ${typeof writeP99 === 'number' ? writeP99.toFixed(2) + 'ms' : writeP99}                                                  ║
║                                                                  ║
║  📖 READ LATENCY (GET /users/:id/metrics)                       ║
║  ─────────────────────────────────────────────────────────       ║
║  p50:  ${typeof readP50 === 'number' ? readP50.toFixed(2) + 'ms' : readP50}                                                  ║
║  p90:  ${typeof readP90 === 'number' ? readP90.toFixed(2) + 'ms' : readP90}                                                  ║
║  p95:  ${typeof readP95 === 'number' ? readP95.toFixed(2) + 'ms' : readP95}   ${typeof readP95 === 'number' && readP95 < 200 ? '✅ PASS' : '❌ FAIL'}                                   ║
║  p99:  ${typeof readP99 === 'number' ? readP99.toFixed(2) + 'ms' : readP99}                                                  ║
║                                                                  ║
╠══════════════════════════════════════════════════════════════════╣
║  VERDICT:                                                        ║
║  Write p95 < 150ms: ${typeof writeP95 === 'number' && writeP95 < 150 ? 'PASS ✅' : 'FAIL ❌'}                                        ║
║  Read  p95 < 200ms: ${typeof readP95 === 'number' && readP95 < 200 ? 'PASS ✅' : 'FAIL ❌'}                                        ║
║  Error Rate < 1%:   ${failedRate < 0.01 ? 'PASS ✅' : 'FAIL ❌'}                                        ║
║  Dropped = 0:       ${dropped === 0 ? 'PASS ✅' : 'FAIL ❌'}                                        ║
╚══════════════════════════════════════════════════════════════════╝
`;

  // Write JSON summary for programmatic access
  const jsonSummary = {
    timestamp: new Date().toISOString(),
    environment: 'native Pop!_OS Docker',
    throughput: {
      totalRequests: totalReqs,
      avgReqPerSec: parseFloat(duration.toFixed(1)),
      writeSuccesses: writeCount,
      readSuccesses: readCount,
      writeErrors: writeErrCnt,
      readErrors: readErrCnt,
      droppedIterations: dropped,
      errorRate: parseFloat((failedRate * 100).toFixed(3)),
    },
    writeLatency: {
      p50: typeof writeP50 === 'number' ? parseFloat(writeP50.toFixed(2)) : null,
      p90: typeof writeP90 === 'number' ? parseFloat(writeP90.toFixed(2)) : null,
      p95: typeof writeP95 === 'number' ? parseFloat(writeP95.toFixed(2)) : null,
      p99: typeof writeP99 === 'number' ? parseFloat(writeP99.toFixed(2)) : null,
    },
    readLatency: {
      p50: typeof readP50 === 'number' ? parseFloat(readP50.toFixed(2)) : null,
      p90: typeof readP90 === 'number' ? parseFloat(readP90.toFixed(2)) : null,
      p95: typeof readP95 === 'number' ? parseFloat(readP95.toFixed(2)) : null,
      p99: typeof readP99 === 'number' ? parseFloat(readP99.toFixed(2)) : null,
    },
    validation: {
      writP95Pass: typeof writeP95 === 'number' && writeP95 < 150,
      readP95Pass: typeof readP95 === 'number' && readP95 < 200,
      errorRatePass: failedRate < 0.01,
      droppedPass: dropped === 0,
    },
  };

  return {
    stdout: summary,
    'loadtest/reports/spec_results.json': JSON.stringify(jsonSummary, null, 2),
  };
}
